### PR TITLE
feat(errors) mark errors inline with a red underline

### PR DESCRIPTION
**Pull request by hishamhm**
This is an ugly WIP (both the code and the output :laughing: ), but that's as far as I could go for now :)

Tried to make the errors appear inline, IDE-style. Based it on this:

https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations

What's done:

- [x] collect errors as separate x, y and message variables usable from the TS side
- [x] reflect the position of the errors as decorations in the editor component
- [x] update those in realtime

What's missing:

- [ ] CSS for nice squiggly IDE-like red underline 
- [ ] extending the underline through the whole token instead of only the first character (is there some Monaco API to get the length of the word at position x,y?)
- [ ] show a tooltip with the error message, like in the Monaco Playground above

I don't plan to pursue these todo items myself as stumbling through TS, Vue and Monaco to get the code to this point was already challenging enough (fun learning experience though!), but hopefully this can be a useful starting point! :grin:

### CODE REVIEW

**Comment by darrenjennings** [comment]
Another potential solution is to write https://github.com/teal-language/vscode-teal in javascript and have monaco load the extension.

**Comment by hishamhm** [comment]
> https://github.com/teal-language/vscode-teal

I haven't looked at it super closely but I think all of the presentation aspects (that are missing in this PR) live in vscode itself and not in the LSP server. @pdesaulniers, do you confirm?

**Comment by pdesaulniers** [comment]
@hishamhm 

> I haven't looked at it super closely but I think all of the presentation aspects (that are missing in this PR) live in vscode itself and not in the LSP server. 

Yeah, that sounds right. The language server simply sends diagnostics to the client. The squiggly lines and tooltips are handled by vscode itself, based on the diagnostics.

>  extending the underline through the whole token instead of only the first character (is there some Monaco API to get the length of the word at position x,y?)

I'm not familiar with standalone Monaco, but in the vscode extension, it was just a matter of creating a range with identical start and end. What happens if you remove the +1 here? https://github.com/teal-language/teal-playground/blob/ecc012f9b6025af550d62503247195f0c555a6ae/src/components/Playground.vue#L116

EDIT: Well, it doesn't seem to work in the Monaco playground! However, this should do the trick:
```ts
var model = editor.getModel();
var word = model.getWordAtPosition(new monaco.Position(y, x));
var range = new monaco.Range(y, word.startColumn, y, word.endColumn);
```

**Comment by pdesaulniers** [comment]
Actually, it seems like the Markers API is more appropriate for displaying errors. This shows a squiggly line and a tooltip in the Monaco Playground:
```js
let model = monaco.editor.createModel("function squiggly() {\n}", "javascript");

monaco.editor.create(document.getElementById("container"), {
    model
});

monaco.editor.setModelMarkers(model, "owner", [
    {
        startLineNumber: 1,
        startColumn: 1,
        endLineNumber: 1,
        endColumn: 1,
        message: "Hello, I am a cute error",
        severity: monaco.MarkerSeverity.Error
    }
]);
```

**Comment by hishamhm** [comment]
Ooh, thanks @pdesaulniers! That worked!

**Comment by darrenjennings** [comment]
nice! it works great, good work! I added a pr to clean it up just slightly. You can see the netlify previews on these PR's as well which is nice to verify it's working.

**Pull request merged**
